name: haskell-servant
version: 0.1.0.0
github: "githubuser/haskell-servant"
license: BSD-3-Clause
author: "Author name here"
maintainer: "example@example.com"
copyright: "2024 Author name here"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/haskell-servant#readme>

dependencies:
  - base >= 4.17 && < 5
  - aeson
  - servant-server
  - servant-websockets
  - servant-openapi3
  - openapi3
  - wai
  - warp
  - servant-blaze
  - blaze-html
  - blaze-markup
  - text
  - cookie
  - bytestring
  - transformers
  - websockets
  - fsnotify
  - lens
  - wai-logger

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  haskell-servant-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - haskell-servant

tests:
  haskell-servant-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - haskell-servant
      - hspec
      - hspec-wai
      - hspec-wai-json
      - aeson
